language: ruby
before_install:
  - sudo mkdir /usr/local/evm
  - sudo chown travis:travis /usr/local/evm

  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
  - sudo apt-get build-dep -qq emacs23
  - sudo apt-get build-dep -qq emacs24

  - bin/evm install $EVM_EMACS
  - bin/evm use $EVM_EMACS
script:
  - bundle exec rspec spec
  - bin/emacs --version
rvm:
  - 1.9.3
env:
  - EVM_EMACS=emacs-23.4-bin
  - EVM_EMACS=emacs-23.4
  - EVM_EMACS=emacs-24.1-bin
  - EVM_EMACS=emacs-24.1
  - EVM_EMACS=emacs-24.2-bin
  - EVM_EMACS=emacs-24.2
  - EVM_EMACS=emacs-24.3-bin
  - EVM_EMACS=emacs-24.3
  - EVM_EMACS=emacs-24.4-bin
  - EVM_EMACS=emacs-24.4
  - EVM_EMACS=emacs-24.5-bin
  - EVM_EMACS=emacs-24.5
  - EVM_EMACS=emacs-git-snapshot